#!/bin/sh

# first init or else it won't work
STATUS="$(LANG=en rfkill list | sed -n 2p | awk '{print $3}')"

icon() {
  if [[ $STATUS == "no" ]]; then
    echo ""
  else
    echo ""
  fi
}

toggle() {
  if [[ $STATUS == "no" ]]; then
    rfkill block all
    notify-send --urgency=normal -i airplane-mode-symbolic "Mode Avion" "Le mode avion a été activé."
  else
    rfkill unblock all
    notify-send --urgency=normal  -i airplane-mode-disabled-symbolic "Mode Avion" "Le mode avion a été désactivé."
  fi
}

if [[ $1 == "toggle" ]]; then
  toggle
else
  while true; do
    STATUS="$(LANG=en rfkill list | sed -n 2p | awk '{print $3}')"
    icon
    sleep 3;
  done
fi
