#!/usr/bin/env bash
# fuck this

XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME/.cache"}
tmp=$XDG_CACHE_HOME/dunst-history.json

declare ids

get_ids() {
  mapfile -t ids < <(dunstctl history | jaq -r ".data[] | .[] | select(.appname.data != \"Spotify\") | .id.data")
}

get_notif() {
  echo -n '['

  for id in "${ids[@]}"; do
      mapfile -t n < <(jaq -r ".data[] | .[] | select(.id.data == $id) | .appname.data, .summary.data, .body.data" "$tmp" | sed -r '/^\s*$/d' | sed -e 's/\%/ percent/g')
      echo -n ''$([ $id -eq ${ids[0]} ] || echo ,)' { '
      echo -n '"id": "'"$id"'", "appname": "'"${n[0]}"'", "summary": "'"${n[1]}"'", "body": "'"${n[2]}"'"'
      echo -n '}' 
  done

  echo ']'
}

toggle() {
  dunstctl set-paused toggle
}

clear() {
  killall dunst && systemctl --user start dunst
}

get_icon() {
  if [ ${#ids[@]} -eq 0 ]; then
    echo ""
  else
    echo ""
  fi
}

get_toggle_icon() {
  if [ "$(dunstctl is-paused)" == false ]; then
    echo ""
  else
    echo ""
  fi
}

get_toggle_text() {
  if [ "$(dunstctl is-paused)" == false ]; then
    echo "Couper les notifications"
  else
    echo "Réactiver les notifications"
  fi
}

if [ "$1" == "toggle" ]; then
  toggle
  dunstctl history > "$tmp"
  echo '{"toggle_icon": "'"$(get_toggle_icon)"'", "icon": "'"$(get_icon)"'", "toggle_text": "'"$(get_toggle_text)"'"}'
elif [ "$1" == "clear" ]; then
  clear
  dunstctl history > "$tmp"
  get_notif
  echo '{"toggle_icon": "'"$(get_toggle_icon)"'", "icon": "'"$(get_icon)"'", "toggle_text": "'"$(get_toggle_text)"'"}'
elif [ "$1" == "icons" ]; then
  dunstctl history > "$tmp"
  get_ids
  echo '{"toggle_icon": "'"$(get_toggle_icon)"'", "icon": "'"$(get_icon)"'", "toggle_text": "'"$(get_toggle_text)"'"}'
  tail -f "$tmp" | while read -r; do
    get_ids
    echo '{"toggle_icon": "'"$(get_toggle_icon)"'", "icon": "'"$(get_icon)"'", "toggle_text": "'"$(get_toggle_text)"'"}'
  done
elif [ "$1" == "notifs" ]; then
  dunstctl history > "$tmp"
  get_ids
  get_notif
  tail -f "$tmp" 2>/dev/null | rg --line-buffered "aa\{sv\}" | while read -r; do
    get_ids
    get_notif
    echo '{"toggle_icon": "'"$(get_toggle_icon)"'", "icon": "'"$(get_icon)"'", "toggle_text": "'"$(get_toggle_text)"'"}'
  done
else
  dunstctl history > "$tmp"
  get_ids
  get_notif
  echo '{"toggle_icon": "'"$(get_toggle_icon)"'", "icon": "'"$(get_icon)"'", "toggle_text": "'"$(get_toggle_text)"'"}'
  tail -f "$tmp" 2>/dev/null | rg --line-buffered "aa\{sv\}" | while read -r; do
    get_ids
    get_notif
    echo '{"toggle_icon": "'"$(get_toggle_icon)"'", "icon": "'"$(get_icon)"'", "toggle_text": "'"$(get_toggle_text)"'"}'
  done
fi
