#!/usr/bin/env bash

volicons=("" "" "")

ismuted() {
  pamixer --get-mute
}
ismicmuted() {
  pamixer --default-source --get-mute
}

# initial values
lvl=$(awk -v n="$(vol)" 'BEGIN{print int(n/34)}')
ismuted=$(ismuted)
ismicmuted=$(ismicmuted)

if [ "$ismuted" = false ]; then
  icon="${volicons[$lvl]}"
else
  icon=""
fi
if [ "$ismicmuted" = false ]; then
  micicon=""
else
  micicon=""
fi
echo '{ "icon": "'"$icon"'", "micicon": "'"$micicon"'", "percent": "'"$(vol)"'", "microphone": "'"$(micvol)"'" }'

# event loop
pactl subscribe | rg --line-buffered "change" | rg --line-buffered "dest" | while read -r _; do
  lvl=$(awk -v n="$(pamixer --get-volume)" 'BEGIN{print int(n/34)}')

  if [[ $(ismuted) == false ]]; then
    icon="${volicons[$lvl]}"
  else
    icon=""
  fi
  if [ $(ismicmuted) == false ]; then
    micicon=""
  else
    micicon=""
  fi
  echo '{ "icon": "'"$icon"'", "micicon": "'"$micicon"'" }'
done
