#!/usr/bin/env bash

volicons=("" "" "")

vol() {
  pamixer --get-volume
}
micvol() {
  pamixer --default-source --get-volume
}
ismuted() {
  pamixer --get-mute
}
ismicmuted() {
  pamixer --default-source --get-mute
}
setvol() {
  pamixer --set-volume $2
}
setmute() {
  pamixer -t
}
setmicvol() {
  pamixer --default-source --set-volume $2
}
setmicmute() {
  pamixer --default-source -t
}

if [ "$1" = "mute" ]; then
  setmute
elif [ "$1" = "micmute" ]; then
  setmicmute
elif [ "$1" = "setvol" ]; then
  if [ "$2" != "SOURCE" ] && [ "$2" != "SINK" ]; then
    echo "Can only set volume for SINK or SOURCE"; exit 1
  elif [ "$3" -lt 1 ] || [ "$3" -gt 100 ]; then
    echo "Volume must be between 1 and 100"; exit 1
  fi
  setvol "$2" "$3"
elif [ "$1" = "setmicvol" ]; then
  if [ "$2" != "SOURCE" ] && [ "$2" != "SINK" ]; then
    echo "Can only set volume for SINK or SOURCE"; exit 1
  elif [ "$3" -lt 1 ] || [ "$3" -gt 100 ]; then
    echo "Volume must be between 1 and 100"; exit 1
  fi
  setmicvol "$2" "$3"
else
  # initial values
  lvl=$(awk -v n="$(vol "SINK")" 'BEGIN{print int(n/34)}')
  ismuted=$(ismuted)
  ismicmuted=$(ismicmuted)

  if [ "$ismuted" = false ]; then
  	icon="${volicons[$lvl]}"
  else
    icon=""
  fi
  if [ "$ismicmuted" = false ]; then
  	micicon=""
  else
    micicon=""
  fi
  echo '{ "icon": "'"$icon"'", "micicon": "'"$micicon"'", "percent": "'"$(vol)"'", "microphone": "'"$(micvol)"'" }'

  # event loop
  pactl subscribe | rg --line-buffered "change" | while read -r _; do
    lvl=$(awk -v n="$(vol)" 'BEGIN{print int(n/34)}')
    ismuted=$(ismuted)
    ismicmuted=$(ismicmuted)

    if [[ "$ismuted" == false ]]; then
    	icon="${volicons[$lvl]}"
    else
      icon=""
    fi
    if [ "$ismicmuted" = false ]; then
      micicon=""
    else
      micicon=""
    fi
    echo '{ "icon": "'"$icon"'", "micicon": "'"$micicon"'", "percent": "'"$(vol)"'", "microphone": "'"$(micvol)"'" }'
  done
fi
